<?php
/*  
 *  Copyright (c) 2012-2014 Jochen S. Klar <jklar@aip.de>,
 *                           Adrian M. Partl <apartl@aip.de>, 
 *                           AIP E-Science (www.aip.de)
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU Affero General Public License as
 *  published by the Free Software Foundation, either version 3 of the
 *  License, or (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU Affero General Public License for more details.
 *
 *  You should have received a copy of the GNU Affero General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
?>

<h2>Credits</h2>

<p>
    Daiquiri is developed and maintained by the E-Science group at the 
    <a href="http://www.aip.de/" target="_blank">Leibniz-Institute for Astrophysics Potsdam</a>.
</p>
<p>
    Lead developers are <a href="http://jochenklar.de/" target="_blank">Jochen Klar</a> and 
    <a href="https://www.adrian-partl.de/" target="_blank">Adrian Partl</a>.
</p>