<?php
/*  
 *  Copyright (c) 2012, 2013 Jochen S. Klar <jklar@aip.de>,
 *                           Adrian M. Partl <apartl@aip.de>, 
 *                           AIP E-Science (www.aip.de)
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  See the NOTICE file distributed with this work for additional
 *  information regarding copyright ownership. You may obtain a copy
 *  of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
?>

<?php echo $this->doctype() ?>
<html>
    <head>
        <meta charset="UTF-8">
        <link rel="icon" href="/favicon.ico" type="image/x-icon">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <?php
        echo $this->headTitle('Daiquiri');
        echo $this->headMeta();
        echo $this->headDaiquiri(array(
            'style.css'
        ));
        ?>
    </head>

    <body>
        <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="navbar-inner">
                <div class="container">
                    <a class="brand" href="<?php echo $this->baseUrl('/'); ?>">
                        <img alt="logo" src="<?php echo $this->baseUrl('img/daiquiri32.png'); ?>" />
                        <h1>Daiquiri</h1>
                    </a>

                    <ul class="nav">
                        <?php
                        echo $this->internalLink(array(
                            'text' => 'Page',
                            'href' => '/index/page',
                            'prepend' => '<li>',
                            'append' => '</li>'));
                        ?>
                        <li class="dropdown">
                            <a class="dropdown-toggle"
                               data-toggle="dropdown"
                               href="#">
                                Examples
                            </a>
                            <ul class="dropdown-menu">
                                <?php
                                $pages = array(
                                    '/examples/row' => 'Row layout',
                                    '/examples/table' => 'Tables',
                                );
                                foreach ($pages as $href => $text) {
                                    echo $this->internalLink(array(
                                        'text' => $text,
                                        'href' => $href,
                                        'prepend' => '<li>',
                                        'append' => '</li>'));
                                }
                                ?>
                            </ul>
                        </li>
                        <?php
                        echo $this->internalLink(array(
                            'text' => 'Credits',
                            'href' => '/credits',
                            'prepend' => '<li>',
                            'append' => '</li>'));
                        echo $this->internalLink(array(
                            'text' => 'Query',
                            'href' => '/query',
                            'prepend' => '<li>',
                            'append' => '</li>'));
                        echo $this->internalLink(array(
                            'text' => 'Contact',
                            'href' => '/contact',
                            'prepend' => '<li>',
                            'append' => '</li>'));

                        echo $this->adminMenu();
                        ?>
                    </ul>
                    <ul class="nav pull-right">
                        <?php echo $this->accountMenu(); ?>
                        <li>
                            <?php echo $this->loginLink(); ?>
                        </li>
                    </ul> 
                </div>
            </div>
        </div>

        <div id="wrapper" class="container">
            <div id="content">
                <?php echo $this->layout()->content; ?>
            </div>
        </div>
    </body>
</html>