<?php
/*  
 *  Copyright (c) 2012-2014 Jochen S. Klar <jklar@aip.de>,
 *                           Adrian M. Partl <apartl@aip.de>, 
 *                           AIP E-Science (www.aip.de)
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU Affero General Public License as
 *  published by the Free Software Foundation, either version 3 of the
 *  License, or (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU Affero General Public License for more details.
 *
 *  You should have received a copy of the GNU Affero General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
?>

<?php echo $this->doctype() ?>
<html>
    <head>
        <meta charset="UTF-8">
        <link rel="icon" href="/favicon.ico" type="image/x-icon">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <base href="<?php echo $this->baseUrl(); ?>">
        <?php
        echo $this->headTitle('Daiquiri');
        echo $this->headMeta();
        echo $this->headStatic(array(
            'style.css'
        ));
        ?>
    </head>

    <body>
        <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="navbar-inner">
                <div class="container">
                    <a class="brand" href="<?php echo $this->baseUrl('/'); ?>">
                        <img alt="logo" src="<?php echo $this->baseUrl('img/daiquiri32.png'); ?>" />
                        <h1>Daiquiri</h1>
                    </a>

                    <ul class="nav">
                        <?php
                        echo $this->internalLink(array(
                            'text' => 'Query',
                            'href' => '/query',
                            'prepend' => '<li>',
                            'append' => '</li>'));
                        echo $this->internalLink(array(
                            'text' => 'Contact',
                            'href' => '/contact',
                            'prepend' => '<li>',
                            'append' => '</li>'));

                        echo $this->adminMenu();
                        ?>
                    </ul>
                    <ul class="nav pull-right">
                        <?php echo $this->accountMenu(); ?>
                        <li>
                            <?php echo $this->loginLink(); ?>
                        </li>
                    </ul> 
                </div>
            </div>
        </div>

        <div id="wrapper" class="container">
            <div id="content">
                <?php echo $this->layout()->content; ?>
            </div>
        </div>
    </body>
</html>